# This is a basic workflow to help you get started with Actions

name: Build app to deploy to Tencent
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # 监听push操作在 master分支
  push:
    branches: [ master ]
jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    # 使用别人的action
    - uses: actions/checkout@v2
    # 步骤名称
    - name: yarn
      # 步骤执行指令
      run: yarn
    - name: yarn build
      run: yarn build
    # 命名这个任务为发布Deploy
    - name: Deploy
      # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
      uses: cross-the-world/scp-pipeline@master
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        connect_timeout: 10s
        local: './dist/*'
        remote: /www/wwwroot/forcoder/dist
